name: CI
on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: '16'

      - name: Setup git
        if: contains(github.event.pull_request.head_commit.message, 'review-release')
        run: |
          git config --global user.name 'antoinelncl'
          git config --global user.email 'lancial.antoine@gmail.com'

      - name: OKLOL
        run: |
          echo ${{ toJson(github.event.pull_request.commits[0]) }}

      - name: Setup npm
        run: |
            npm config set "//npm.pkg.github.com/:_authToken" "${NODE_AUTH_TOKEN}"
            npm config set registry https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Install packages dependencies
        run: npx nx affected --base=last-release --target=install

      - name: Build
        shell: bash
        run: npx nx affected --base=last-release --target=build --verbose

      - name: Tests
        shell: bash
        run: npx nx affected --base=last-release --target=test --verbose

      - name: Publish Alpha
        if: contains(github.event.pull_request.head_commit.message, 'review-release')
        shell: bash
        run: npx nx affected --base=alpha --target=alphaVersion --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
