name: Release Alpha
on:
  pull_request:
    types:
      - labeled

jobs:
  release-alpha:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'review build')
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: '16'

      - name: Setup git
        run: |
          git config --global user.name 'antoinelncl'
          git config --global user.email 'lancial.antoine@gmail.com'

      - name: Setup npm
        run: |
            npm config set "//npm.pkg.github.com/:_authToken" "${NODE_AUTH_TOKEN}"
            npm config set registry https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Install packages dependencies
        run: npx nx affected --base=alpha --target=install

      - name: Build
        shell: bash
        run: npx nx affected --base=alpha --target=build --verbose

      - name: Tests
        shell: bash
        run: npx nx affected --base=alpha --target=test --verbose

      - name: Publish Alpha
        shell: bash
        run: npx nx affected --base=alpha --target=alphaVersion --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Tag alpha
        shell: bash
        run: |
          git tag -f alpha
          git push origin alpha --force
